# Generated by Django 3.0 on 2019-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirrurl',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
