# Generated by Django 3.0 on 2019-12-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_wirrurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
